### ISSUE TITLE
Crash in server.js

### ISSUE THREAD

**Issue by DenisROBERT1** [jhudsy/LoebnerPrizeProtocol#14]
Crash in server.js when judge.html is launched

>      ^
> 
> TypeError: Cannot read property 'judge0' of undefined
>     at handleControlMessage (C:\server\server.js:239:76)
>     at Socket.<anonymous> (C:\server\server.js:396:38)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at C:\server\node_modules\socket.io\lib\socket.js:503:12
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> 

To correct it, I had to change server.js:239

`if (messages[currentRound][c]!=undefined){`

by

`if (messages[currentRound]!=undefined && messages[currentRound][c]!=undefined){`

**Comment by jhudsy** [comment]
Hi,

I'm struggling to replicate this on my setup; while the fix you suggest will work, I wonder if the problem is that currentRound is -1, and checking for that would be better; would you be able to add a print statement to print it out and let me know if this is the case or not?

Thanks

**Comment by DenisROBERT1** [comment]
I have added a print just before the crash, and in fact currentRound is equal to -1. It happens when the judge is connecting and send the request "recap" (the first connection is the control panel) :

Connection detected
Connection detected
{"status":"register","id":"judge0","secret":"alice"}
{"status":"roundInformation","id":"judge0","secret":"alice"}
{"status":"recap","id":"judge0","secret":"alice"}
currentRound = -1
C:\Sources\TALN\LoebnerPrizeProtocole\server\server.js:240
                  if (messages[currentRound][c]!=undefined){ //undefined if roun
d hasn't started, so just don't respond
TypeError: Cannot read property 'judge0' of undefined
